version: "3.8"

services:

  back:
    build: back
    networks:
      calcHub:
        ipv4_address: 172.168.0.2
    volumes:
      - ./back:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      
  front:
    build: front
    networks:
      calcHub:
        ipv4_address: 172.168.0.3
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "3000:3000"

networks:
  calcHub:
    ipam:
      config:
        - subnet: 172.168.0.0/24
          gateway: 172.168.0.1